
name: GitHub Actions CI Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: springboot
  IMAGE_TAG: ${{ github.run_id }}
  ACR_NAME: venkateshacr.azurecr.io

jobs:
  build-deploy:
    name: Build and Deploy Spring boot for beginner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          # Container registry username
          username: ${{ secrets.ACR_USERNAME }}
          # Container registry password
          password: ${{ secrets.ACR_PASSWORD }}
          # Container registry server url
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          
      - run: |
          docker build . --file Dockerfile --tag $IMAGE_NAME:$IMAGE_TAG
          docker push venkateshacr.azurecr.io/springboot
 

