
name: GitHub Actions CI Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: springboot
  IMAGE_TAG: ${{ github.run_id }}
  ACR_NAME: venkateshacr.azurecr.io

jobs:
  ci-build:
    name: Build and Deploy Spring boot for beginner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          # Container registry username
          username: ${{ secrets.ACR_USERNAME }}
          # Container registry password
          password: ${{ secrets.ACR_PASSWORD }}
          # Container registry server url
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          
      - run: |
          docker build . -t venkateshacr.azurecr.io/springboot:${{ github.run_id }}
          docker push venkateshacr.azurecr.io/springboot:${{ github.run_id }}

  cd-deploy:
    name: Deploy to Azure WebApp
    runs-on: ubuntu-latest
    needs: ci-build
    steps:
      - name: Azure Login
        uses: Azure/login@v2.0.0
        with:
          # az ad sp create-for-rbac --name "{sp-name}" --sdk-auth
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Deploy to Azure WebApp
        uses: Azure/webapps-deploy@v3.0.1
        with:
          app-name: venkateshcontainers        
          images:  venkateshacr.azurecr.io/springboot:${{ github.run_id }}
